### PR TITLE
I modified the regular expression used in validate.

### LINKED ISSUE #90: Box name is wrongly validated
Not only it is [wrongly encoded](https://github.com/personium/app-uc-unit-manager/blob/master/src/js/boxProfile.js#L360), it is also wrong in logic.  

Correct specification [here](https://personium.io/docs/ja/apiref/current/256_Create_Box.html)

### PR DESCRIPTION
**Pull request by csKyou**
close #90 #91 #92 #93

### CODE REVIEW

File: src/js/odata.js [hunk 1]
```diff
@@ -1597,22 +1597,22 @@ odata.prototype.errorHandler = function(evt) {
...
     if (fileName.indexOf("fakepath") != -1) {
         fileName = fileName.substring(fileName.lastIndexOf("fakepath") + 9);
     }
     var fileLength = fileName.length;
     objOdata.fileType = fileName.substring(fileName.lastIndexOf('.') + 1);
-    if (fileLength > 128) {
+    if (fileLength > 256) {
         objOdata.spinner.stop();
         document.getElementById("dvGreyOut").style.display = 'none';
         alert("File name can not exceed 128 characters");
```
Comment (dixonsiu) [inline src/js/odata.js]: Please change to 256

File: src/js/cellProfile.js [hunk 2]
```diff
@@ -100,10 +100,8 @@ cellProfile.prototype.removeStatusIcons = function (txtID) {
  */
 cellProfile.prototype.validateDisplayName = function (displayName, displayNameSpan,txtID) {
     var MINLENGTH = 1;
-    var MAXLENGTH = 128;
-    var letters = /^[一-龠ぁ-ゔ[ァ-ヴー々〆〤0-9a-zA-Z-_]+$/;
-    var specialchar = /^[-_]*$/;
-    var allowedLetters = /^[0-9a-zA-Z-_]+$/;
+    var MAXLENGTH = 256;
```
Comment (dixonsiu) [inline src/js/cellProfile.js:103]: Please fix the condition checking
from: lenDisplayName >= MAXLENGTH
to: lenDisplayName > MAXLENGTH

File: src/js/odata.js (hunk 1 above)
Comment (dixonsiu) [inline src/js/odata.js]: Please change message to the following.
"File name cannot exceed 256 characters"

File: src/js/uBox.js [hunk 3]
```diff
@@ -919,21 +919,24 @@ function displaySuccessMessage(modalId,dvMessageID) {
...
-    	showErrorIcon(txtDisplayName);
+    var MINLENGTH = 1;
+    var MAXLENGTH = 256;
+    var letters = new RegExp("^[^" + objCommon.getValidateBlackList() + "]+$");
+    var lenDisplayName = displayName.length;
+    if(lenDisplayName < MINLENGTH || displayName == undefined || displayName == null || displayName == "") {
+        showErrorIcon(txtDisplayName);
+        $("#" + displayNameSpan).html(getUiProps().MSG0103);
+        return false;
+    } else if (lenDisplayName >= MAXLENGTH) {
```
Comment (dixonsiu) [inline src/js/uBox.js]: Fix checking condition.

**Review by dixonsiu — CHANGES_REQUESTED** [review]

**Review by dixonsiu — APPROVED** [review]
